## Tensor Basics


In [2]:
import torch
x = torch.empty(3) # 1D 3element
x = torch.empty(2, 3) # 2D 2x3 element
print(x)

# Random Value
x = torch.rand(2,2)
print(x)

# Init with zeros
x = torch.zeros(2,2)

# data type
x = torch.ones(2,2, dtype=torch.int)
print(x.dtype)
# size
print(x.size())

# construct tensor from data(list)
x = torch.tensor([1,2,3,4,5]) 
print(x)

# Basic Operation
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

# addition (element-wise)
z = x + y
print(z)
z = torch.add(x,y)
print(z)

# Inplace Addition
# _ : 뒤에 _ 가 붙은 함수들은 모두 Inplace다 (pytorch)
y.add_(x)
print(y) 

# subtraction
z = x - y
z = torch.sub(x,y)
y.sub_(x)
print(z)
print(y)

# multiplication(element-wise)
z = x * y
y.mul_(x)

# division
z = x / y
y.div_(x)



tensor([[9.8091e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0.5892, 0.2655],
        [0.6880, 0.6516]])
torch.int32
torch.Size([2, 2])
tensor([1, 2, 3, 4, 5])
tensor([[0.6382, 0.5643],
        [0.8610, 0.7880]])
tensor([[0.9396, 0.8182],
        [0.2867, 0.7852]])
tensor([[1.5777, 1.3825],
        [1.1477, 1.5733]])
tensor([[1.5777, 1.3825],
        [1.1477, 1.5733]])
tensor([[1.5777, 1.3825],
        [1.1477, 1.5733]])
tensor([[-0.9396, -0.8182],
        [-0.2867, -0.7852]])
tensor([[0.9396, 0.8182],
        [0.2867, 0.7852]])


tensor([[0.9396, 0.8182],
        [0.2867, 0.7852]])

In [3]:
# Slicing
x = torch.rand(5, 3)
print(x)
print(x[:, 0]) # First Column only
print(x[1,1].item()) # actual value

# Reshape
x = torch.rand(4,4)
print(x)
y = x.view(16) # rows first, next column
print(y)

print('hi')
x = torch.rand(4,4,2)
print('x',x)
y = x.view(2,2,-1)
print('y',y)



tensor([[0.5900, 0.2030, 0.9967],
        [0.1699, 0.4666, 0.2772],
        [0.7756, 0.1144, 0.2404],
        [0.9936, 0.5325, 0.1933],
        [0.4150, 0.1627, 0.3187]])
tensor([0.5900, 0.1699, 0.7756, 0.9936, 0.4150])
0.4665902256965637
tensor([[0.6789, 0.9774, 0.7704, 0.3079],
        [0.0713, 0.4667, 0.6146, 0.4676],
        [0.7145, 0.4698, 0.8758, 0.3693],
        [0.6303, 0.7538, 0.3405, 0.8490]])
tensor([0.6789, 0.9774, 0.7704, 0.3079, 0.0713, 0.4667, 0.6146, 0.4676, 0.7145,
        0.4698, 0.8758, 0.3693, 0.6303, 0.7538, 0.3405, 0.8490])
hi
x tensor([[[0.6756, 0.0760],
         [0.8720, 0.1841],
         [0.6849, 0.1104],
         [0.0944, 0.1235]],

        [[0.6058, 0.4102],
         [0.7770, 0.9856],
         [0.2843, 0.0643],
         [0.7972, 0.1510]],

        [[0.8841, 0.9820],
         [0.6255, 0.7271],
         [0.0894, 0.5003],
         [0.5597, 0.6298]],

        [[0.2430, 0.2551],
         [0.5415, 0.2782],
         [0.7967, 0.5748],
         [0.8608, 0.7004]]])
y 

In [4]:
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy()
print(b,type(b))

# if tensor is on the CPU; NOT GPU -> same memory
a.add_(1)
print(b)

print(torch.backends.mps.is_available())
device = 'mps'
a = torch.ones(1,device=device)
b = a.numpy()
print(b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
[2. 2. 2. 2. 2.]
True


TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
c = torch.tensor(a)
print(c)

a += 1
print(a)
print(b)
print(c)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [18]:

if torch.backends.mps.is_available():
    device = torch.device('mps')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to('cpu') # z.cpu()
    z = z.numpy()
    print(z)


[2. 2. 2. 2. 2.]


In [21]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
