In [1]:
import torch

### HI


In [50]:
torch.random.manual_seed(8)

x = torch.randn(3, requires_grad=True) # requires_grad=True -> Gradient가 생김 개신기
print(x)

y = x + 2
print(y) # tensor([,,], grad_fn = <AddBackward0>)
z = y*y*2
print(z) # MulBackward0
z = z.mean()
print(z)

# 기본적으로 backward()는 output이 scalar야 가능함. 만약에 output이 1d n-array일 경우, n크기의 벡터 v를 만들면, 가능
# z = z[0]*0.01 + z[1] + z[2]*0.001 한거랑 똑같은듯
'''
v = torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
z.backward(v)
'''

z.backward() # -> Outputs Should be Scalar! 
print(x.grad)

tensor([ 0.2713, -1.2729,  0.5027], requires_grad=True)
tensor([2.2713, 0.7271, 2.5027], grad_fn=<AddBackward0>)
tensor([10.3174,  1.0573, 12.5270], grad_fn=<MulBackward0>)
tensor(7.9672, grad_fn=<MeanBackward0>)
tensor([3.0284, 0.9694, 3.3369])


In [46]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)
'''
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():
'''

# x.requires_grad_(False)
# print(x)

# y = x.detach()
# print(y)

with torch.no_grad():
    y = x + 2
    print(y)


tensor([0.8988, 1.0884, 0.1770], requires_grad=True)
tensor([2.8988, 3.0884, 2.1770])
tensor([4.8988, 5.0884, 4.1770])


In [49]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)
    weights.grad.zero_()

    weights


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights)
optimizer.step()
optimizer.zero_grad()