## Gradient Descent with Autograd and Back-propagation
- prediction: Manually
- Gradients Computation: Manually
- Loss Computation: Manually
- Parameter updates: Manually



In [2]:
import numpy as np
import torch

In [ ]:
# f = w * x

# f = 2 * x
X = np.array([1,2,3,4],dtype = np.float32)
Y = np.array([2,4,6,8],dtype = np.float32)

w = 0.0

# model prediction
def forward(x):
    return w * X

# loss 
def loss(y, y_hat):
    return ((y - y_hat)**2).mean()

# gradient 
# MSE = 1/N * (wx - y)^2
# dJ/dw = 1/N 2x (wx- y)
def gradient(x, y, y_hat):
    '''
    y1_hat = w * x1
    y2_hat = w * x2
    y3_hat = w * x3
    y4_hat = w * x4
    J = 1/N * SUM[(y_i - y_i_hat)^2] = 1/N * [(y1 - y1_hat)^2 + (y2 - y2_hat)^2 + (y3 - y3_hat)^2 + (y4 - y4_hat)^2]
    
    '''
    return np.dot(2*x, y_hat-y).mean() # 영상에서는 이렇게 하라는데, 내적한다라..



In [16]:
import numpy as np
import torch
a = np.array([2,2,2,2])
b = np.array([3,3,3,3])

a = torch.ones(3,4)*2
b = torch.ones(4,2)*2
print(a@b)

# c = np.dot(a,np.transpose(b))
# print(c)

# d = a*b
# print(d)

arr = np.array([[1,2,3,4],[3,4,5,6]])
print(arr)
print(np.linalg.inv(arr))

tensor([[16., 16.],
        [16., 16.],
        [16., 16.]])
[[1 2 3 4]
 [3 4 5 6]]


LinAlgError: Last 2 dimensions of the array must be square