## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals

### Lectures
- 12. Getting set up to write pytorch code 
~
- 

In [3]:
import torch
import numpy as np

print(torch.backends.mps.is_available())

print(torch.__version__)

True
1.13.1


/Users/hyunsukim/miniconda3/envs/python-study/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using [`torch.Tensor()`](https://pytorch.org/docs/stable/tensors.html)



In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX[0][0]

tensor(7)

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [4, 5, 6]],
                        [[2, 3, 4],
                        [3, 6, 2],
                        [4, 5, 6]],
                        [[4, 5, 3],
                        [3, 6, 9],
                        [4, 5, 6]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [4, 5, 6]],

        [[2, 3, 4],
         [3, 6, 2],
         [4, 5, 6]],

        [[4, 5, 3],
         [3, 6, 9],
         [4, 5, 6]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([3, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 5, 6]])

In [20]:
TENSOR[1]

tensor([[2, 3, 4],
        [3, 6, 2],
        [4, 5, 6]])

### Summarise

scalar: 0dim, lowercase (ex : a)
vector :1dim, lowercae (ex: y)
matrix: 2dim, Uppercase (ex: Q)
Tensor: can be any number, Uppercase (ex: T)

## Random tensors

Why Random Tensors?


Random tensors are important because the way many neraul networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [21]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.3311, 0.5085, 0.0885, 0.6580],
        [0.3865, 0.3699, 0.2889, 0.1567],
        [0.6437, 0.9552, 0.7145, 0.9822]])

In [22]:
random_tensor.ndim

2

In [23]:
# Create a random tensor with similar shpae to an iamge
random_image_size_tensor = torch.rand(size=(224, 224, 3,)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and ones

In [24]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### Range
#### Creating a range of tensors and tensors-like

In [28]:
torch.__version__

'1.13.1'

In [29]:
# use torch.range()
torch.range(0, 10)

/var/folders/m3/gc3jv3513p9b_6y82p_46vmw0000gn/T/ipykernel_72030/4106555132.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
torch.arange(start=1, end=10, step=2)

tensor([1, 3, 5, 7, 9])

In [32]:
# Creating Tensors Like
one_to_ten_like = torch.zeros_like(input=one_to_ten)
one_to_ten_like.shape, one_to_ten.shape

(torch.Size([10]), torch.Size([10]))

### Tensor data types

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # What data type is the tensor( e.g. float32, float16, int8)
                                device='cpu', # 디바이스
                                requires_grad=False) # operation gradients

float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

## Precision in computing

in CS, the precision of a numerical quantity is a measore of the detail in which the quantity is expressed. 
Single precision 32bits in Computuer memeory (32 bit float -> single precision , 16bit -> half precision)


## Tensor Datatypes
**Note:** Tensor datatypes is one of the 3 big errors
1. Tensors not right datatype
2. not right shape
3. not right device

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_scalar = torch.tensor(1.231231231,dtype=torch.float16)
float_32_scalar = torch.tensor(1.231231231,dtype=torch.float32)
float_16_scalar.item(), float_32_scalar.item()

(1.2314453125, 1.2312312126159668)

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. torch.dtype for data type
2. torch.shape for shape
3. torch.device for device

In [39]:
some_tensor = torch.randn(3, 4)
some_tensor

tensor([[ 0.8546, -1.4674,  1.8471, -1.6603],
        [-1.7010,  2.1963,  1.4835, -0.1373],
        [-0.2410, -1.0774, -0.1860,  0.1734]])

In [40]:
some_tensor.dtype, some_tensor.shape, some_tensor.device


(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
& Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [41]:
# Create a tensor and add 100
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [42]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [43]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [44]:
# PyTroch in-built function
tensor.mul(10)
tensor.mul_(10)
torch.mul(tensor, 10)

tensor([100, 200, 300])

### Matrix Multiplication

Two main ways of performing multiplication in NN and eep learning:
1. Element-wise multiplication
2. Matrix Multiplication

In [45]:
# Element wise Multiplication
tensor * tensor

tensor([100, 400, 900])

In [46]:
# Matrix Mutliplication
torch.matmul(tensor,tensor)
tensor @ tensor

tensor(1400)

In [47]:
# Matrix Multiplication by hand
1 * 1 + 2 * 2 + 3* 3

14

In [48]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value

CPU times: user 394 µs, sys: 406 µs, total: 800 µs
Wall time: 454 µs


tensor(1400)

In [49]:
%%time


torch.matmul(tensor,tensor)

CPU times: user 83 µs, sys: 29 µs, total: 112 µs
Wall time: 111 µs


tensor(1400)

### One of the most common erros in deep learning: SHAPE ERROR

Two main Rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2) : (2,2)`

In [50]:
torch.matmul(torch.rand(3,2),torch.rand(2,10))

tensor([[0.5916, 0.1580, 0.7611, 0.4703, 0.1640, 0.7477, 0.3873, 0.7369, 0.1646,
         0.3878],
        [0.3247, 0.2799, 0.8643, 0.8639, 0.2622, 0.9543, 0.5065, 0.6452, 0.2285,
         0.8194],
        [0.6553, 0.3065, 1.1469, 0.9332, 0.2989, 1.1984, 0.6291, 0.9801, 0.2763,
         0.8423]])

In [51]:
# Shapes for matrix Multiplication

tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

# torch.mm() # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.mm(tensor_A, tensor_B.t())

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [52]:
tensor_B.size(), tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A transpose switches the axes or diemensions of a given tensor

In [53]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [54]:
## SS
test = torch.arange(1,61)
test = test.view(3,4,5)


# Permute은 element 순서 자체도 바뀜. 하지만 View는 유지
test.shape, test.T[0], test.permute(2,1,0)[0], test.view(5,4,3)[0],test

/var/folders/m3/gc3jv3513p9b_6y82p_46vmw0000gn/T/ipykernel_72030/1796962038.py:7: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1670525498485/work/aten/src/ATen/native/TensorShape.cpp:3281.)
  test.shape, test.T[0], test.permute(2,1,0)[0], test.view(5,4,3)[0],test


(torch.Size([3, 4, 5]),
 tensor([[ 1, 21, 41],
         [ 6, 26, 46],
         [11, 31, 51],
         [16, 36, 56]]),
 tensor([[ 1, 21, 41],
         [ 6, 26, 46],
         [11, 31, 51],
         [16, 36, 56]]),
 tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]],
 
         [[21, 22, 23, 24, 25],
          [26, 27, 28, 29, 30],
          [31, 32, 33, 34, 35],
          [36, 37, 38, 39, 40]],
 
         [[41, 42, 43, 44, 45],
          [46, 47, 48, 49, 50],
          [51, 52, 53, 54, 55],
          [56, 57, 58, 59, 60]]]))

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [55]:
# create a tensor
x = torch.arange(1, 100, 10)
x.dtype

torch.int64

In [56]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [57]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [58]:
%%time
# Find the mean
# torch.mean(x, dtype=torch.float32)
# torch.mean(x.type(torch.float32))
x.type(torch.float16).mean()

CPU times: user 266 µs, sys: 243 µs, total: 509 µs
Wall time: 312 µs


tensor(46., dtype=torch.float16)

In [59]:
# Find the sum
torch.sum(x), x.sum()


(tensor(460), tensor(460))

## Finding the positional min and max


In [60]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [61]:
# Find the position in the tensor that has the minimum value with argmin() -> returns index position of target
x.argmin()

tensor(0)

In [62]:
# Find the mosition in tensor that hs the maximum value with argmax()
x.argmax()

tensor(9)

In [63]:
x[9]

tensor(91)

In [64]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensors to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* unSqueeze - add a `1` dim to a target tensor
* permute - return a view of the input with dimensions permuted (sapped) in a certain way

In [65]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# Change the view -> same memery as the original input (x)
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [68]:
# z는 x의 view라서 메모리를 공유함
z[:, 0] = 5
z, x 

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [69]:
# Stack tensors on top of each other
x_stacked = torch.stack([x.unsqueeze(0),x.unsqueeze(0),x.unsqueeze(0),x.unsqueeze(0),], dim=0)
x_stacked

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [70]:
# squeeze -> Same Memory
x_squeezed = x_stacked.squeeze()
x_stacked.shape,x_stacked.squeeze(), x_stacked.squeeze().shape

(torch.Size([4, 1, 9]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [71]:
x_squeezed[0][0] = 1
x_squeezed, x_stacked


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]))

In [72]:
# torch.permute - Same memory
x_orginial = torch.randn(size=(224, 224, 3)) #[height, width, colour_channels(RGB)]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_orginial.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f'Previous shape:{x_orginial.shape}')
print(f'New Shape: {x_permuted.shape}')

Previous shape:torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [107]:
x_orginial[0,0,0] = 123
x_orginial[0,0,0], x_permuted[0,0,0]

(tensor(123.), tensor(123.))

# Indexing
    | Selecting data from tensors

indexing with pytorch is similar to indexing with NumPy

In [104]:
# Createa a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
# outer bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
# middle Bracket (dim = 1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [77]:
# inner bracket (last dim)
x[0, 1, 2]

tensor(6)

In [78]:
# can use ":" to select all of target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [79]:
# Get all Values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [80]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

## Pytorch tensors & Numpy

Numpy is a popular scientific python numerical computing library.

And because of this, pytorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [81]:
# NumPy Array to tensor
import numpy as np
import torch

# Float64 -> default NumPy Data type

array = np.arange(1.0, 8.0)
tensor = torch.tensor(array)
tensor_f_n = torch.from_numpy(array)
tensor_f_n_32 = torch.from_numpy(array).type(torch.float32)

tensor[0] = 0
tensor_f_n[0] = 3
tensor_f_n_32[0] = 32

# from numpy -> orignial 과 동일한 메모리이지만, dtype을 바꿀 경우 새로 만듬.

array, tensor, tensor_f_n,tensor_f_n_32




(array([3., 2., 3., 4., 5., 6., 7.]),
 tensor([0., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([3., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([32.,  2.,  3.,  4.,  5.,  6.,  7.]))

In [82]:
tensor_f_n.dtype, tensor_f_n_32.dtype, array.dtype, tensor.dtype

(torch.float64, torch.float32, dtype('float64'), torch.float64)

In [100]:
# Chage the value of array, what will this do to 'tensor'?

array = array + 1
print(array, tensor, tensor_f_n, tensor_f_n_32)

tensor_f_n = tensor_f_n + 2
print(array, tensor, tensor_f_n, tensor_f_n_32)

print(array is tensor_f_n)

[5. 4. 5. 6. 7. 8. 9.] tensor([0., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) tensor([5., 4., 5., 6., 7., 8., 9.], dtype=torch.float64) tensor([32.,  2.,  3.,  4.,  5.,  6.,  7.])
[5. 4. 5. 6. 7. 8. 9.] tensor([0., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) tensor([ 7.,  6.,  7.,  8.,  9., 10., 11.], dtype=torch.float64) tensor([32.,  2.,  3.,  4.,  5.,  6.,  7.])
False


## Reproducbility (trying to take random out of random)

[pytorch.manual_seed](https://pytorch.org/docs/stable/notes/randomness.html)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random num to tray and make them better representataions of the data -> again -> ... `

To reduce the randomness in NN and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is 'flavour' the randomness

In [84]:
# 실행시킬때 마다 새로운 랜덤 숫자를 줌...
torch.rand(3, 3)

tensor([[0.4724, 0.3656, 0.3799],
        [0.9529, 0.0132, 0.8503],
        [0.2219, 0.7998, 0.9310]])

In [85]:
# Create two random tensors
random_tensor_A = torch.randn(3, 4)
random_tensor_B = torch.randn(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[ 0.7667, -1.2694,  1.3980,  1.4200],
        [ 0.1936, -1.4756, -0.6068, -1.9233],
        [ 1.0280,  1.6009, -0.8622,  0.9882]])
tensor([[ 0.6090, -0.5888, -0.5132,  2.6157],
        [-0.6621, -1.1979, -0.0706,  0.7310],
        [ 0.4848,  0.2265, -0.0631, -0.2832]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [108]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 77
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # Rand 호출 전에 다시 seed를 또 콜해주면 동일한 tensor가 만들어지네요..!
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)
print(random_tensor_C is random_tensor_D)

tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
False


## Running Tensors and PyTorch objects on the GPUs (and making faster computataions)

GPUs= Faster Computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch 

### 1. Getting a GPU

1. Easiest - use Google Colab for free GPU
2. Use your own GPU - takes a little bit of setup and investment.
3. Use Cloud Computing

### 2. Check for GPU access with PyTorch

In [110]:
import torch
torch.backends.mps.is_available()
# torch.cuda.is_available()

True

In [112]:
device = 'mps' if torch.backends.mps.is_available() else 'cpu'
device

'mps'

In [130]:
# with that been said
# Count number of devices

a = torch.ones(1,device=torch.device('mps:3'))
a

tensor([1.], device='mps:0')

### 3. Putting tensors (and models) on the GPU


In [133]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device='cpu')

# Tensor Not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [134]:
# Move tensor to GPU (if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu 


tensor([1, 2, 3], device='mps:0')

### Moving Tensors Back to the CPU

In [136]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [146]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu[1] = 3
tensor_on_cpu, tensor_on_gpu

(array([1, 3, 4]), tensor([1, 2, 4], device='mps:0'))

In [144]:
tensor_on_gpu[2] = 4
tensor_on_gpu, tensor

(tensor([1, 2, 4], device='mps:0'), tensor([1, 2, 3]))

In [145]:
tensor_on_gpu

tensor([1, 2, 4], device='mps:0')

## Exercise and Extra-curriulum